#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import DBYSDK_dylib;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DBYSharedVideo",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class DBYAuthInfo;
@protocol UIViewControllerTransitionCoordinator;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC14DBYSharedVideo16DBY1VNController")
@interface DBY1VNController : UIViewController
@property (nonatomic, strong) DBYAuthInfo * _Nullable authinfo;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIColor;

SWIFT_CLASS("_TtC14DBYSharedVideo9DBYButton")
@interface DBYButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)setBackgroudnStyleWithFillColor:(UIColor * _Nonnull)fillColor strokeColor:(UIColor * _Nonnull)strokeColor radius:(CGFloat)radius;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo16DBYGlobalMessage")
@interface DBYGlobalMessage : NSObject
+ (DBYGlobalMessage * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)showText:(NSString * _Nonnull)text;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo17DBYLiveController")
@interface DBYLiveController : DBY1VNController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

























@class DBYLiveManager;
@class UIView;
@class DBYInteractionModel;

@interface DBYLiveController (SWIFT_EXTENSION(DBYSharedVideo)) <DBYLiveManagerDelegate>
- (void)clientOnline:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid nickName:(NSString * _Null_unspecified)nickName userRole:(int32_t)role;
- (void)liveManagerClassOver:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager hasNewChatMessageWithChatArray:(NSArray * _Null_unspecified)newChatDictArray;
- (void)liveManagerChatMessageShouldClear:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager hasAnnounceContent:(NSString * _Null_unspecified)announceContent;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager onlineUserCountWith:(NSInteger)count;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager studentCanSpeak:(BOOL)canSpeak;
- (void)liveManagerTeacherDownHands:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager shouldShowVoteWithType:(DBYLiveManagerVoteType)voteType;
- (void)liveManagerShouldStopVote:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManagerShouldHideVote:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager voteChangeWithOptionIndex:(NSInteger)index optionCount:(NSInteger)count;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager voteEndWithOptionIndex:(NSInteger)index ontionSumCount:(NSInteger)count;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager teacherStatusChangedWithOnline:(BOOL)online name:(NSString * _Null_unspecified)name;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager teacherGiveMicToStudentWithUserInfo:(NSDictionary * _Null_unspecified)userInfo canSpeak:(BOOL)canSpeak;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager hasVideo:(BOOL)hasVideo inView:(UIView * _Null_unspecified)view;
- (void)liveManagerDidKickedOff:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManagerTeacherAskStudentOpenCamera:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager denyChatStatusChange:(BOOL)isDeny;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager canChat:(BOOL)canChat;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager receivedQuestion:(NSDictionary * _Null_unspecified)dict;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager removedQuestion:(NSString * _Null_unspecified)questionId;
- (void)initVideoRecorder:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid SWIFT_METHOD_FAMILY(none);
- (void)destroyVideoRecorder:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager interActionListChange:(NSArray<DBYInteractionModel *> * _Null_unspecified)list type:(DBYInteractionType)type;
- (void)willReceivedVideoData:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid;
- (void)willInterruptVideoData:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager thumbupWithCount:(NSInteger)count userName:(NSString * _Null_unspecified)userName;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo21DBYPlaybackController")
@interface DBYPlaybackController : DBY1VNController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo20DBYOfflineController")
@interface DBYOfflineController : DBYPlaybackController
@property (nonatomic, copy) NSString * _Nullable roomID;
@property (nonatomic, copy) NSString * _Nullable offlineKey;
@property (nonatomic, copy) NSString * _Nullable classFilePath;
@property (nonatomic) BOOL hasVideo;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end







@class DBYOfflinePlayBackManager;

@interface DBYOfflineController (SWIFT_EXTENSION(DBYSharedVideo)) <DBYOfflinePlayBackManagerDelegate>
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager thumbupWithCount:(NSInteger)count;
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager playStateIsPlaying:(BOOL)isPlaying;
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager hasVideo:(BOOL)hasVideo inView:(UIView * _Null_unspecified)view;
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager hasNewChatMessageWithChatArray:(NSArray * _Null_unspecified)newChatDictArray;
- (void)offlinePlayBackManagerChatMessageShouldClear:(DBYOfflinePlayBackManager * _Null_unspecified)manager;
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager isPlayingAtProgress:(float)progress time:(NSTimeInterval)time;
- (void)offlinePlayBackManagerFinishedPlay:(DBYOfflinePlayBackManager * _Null_unspecified)manager;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo19DBYOnlineController")
@interface DBYOnlineController : DBYPlaybackController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end









@class DBYOnlinePlayBackManager;

@interface DBYOnlineController (SWIFT_EXTENSION(DBYSharedVideo)) <DBYOnlinePlayBackManagerDelegate>
- (void)playBackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager onlineWithuserId:(NSString * _Null_unspecified)uid nickName:(NSString * _Null_unspecified)nickName userRole:(int32_t)role;
- (void)playBackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager thumbupWithCount:(NSInteger)count;
- (void)playbackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager playStateChange:(BOOL)isPlaying;
- (void)playbackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager hasNewChatMessageWithChatArray:(NSArray * _Null_unspecified)newChatDictArray;
- (void)playBackManagerChatMessageShouldClear:(DBYOnlinePlayBackManager * _Null_unspecified)manager;
- (void)playBackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager totalTime:(NSTimeInterval)time;
- (void)playBackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager playedAtTime:(NSTimeInterval)time;
- (void)playbackManagerDidPlayEnd:(DBYOnlinePlayBackManager * _Null_unspecified)manager;
- (void)playbackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager hasVideo:(BOOL)hasVideo inView:(UIView * _Null_unspecified)view;
@end



SWIFT_CLASS("_TtC14DBYSharedVideo17DBYViewController")
@interface DBYViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibName OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

















#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import DBYSDK_dylib;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DBYSharedVideo",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class DBYAuthInfo;
@protocol UIViewControllerTransitionCoordinator;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC14DBYSharedVideo16DBY1VNController")
@interface DBY1VNController : UIViewController
@property (nonatomic, strong) DBYAuthInfo * _Nullable authinfo;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIColor;

SWIFT_CLASS("_TtC14DBYSharedVideo9DBYButton")
@interface DBYButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)setBackgroudnStyleWithFillColor:(UIColor * _Nonnull)fillColor strokeColor:(UIColor * _Nonnull)strokeColor radius:(CGFloat)radius;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo16DBYGlobalMessage")
@interface DBYGlobalMessage : NSObject
+ (DBYGlobalMessage * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)showText:(NSString * _Nonnull)text;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo17DBYLiveController")
@interface DBYLiveController : DBY1VNController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

























@class DBYLiveManager;
@class UIView;
@class DBYInteractionModel;

@interface DBYLiveController (SWIFT_EXTENSION(DBYSharedVideo)) <DBYLiveManagerDelegate>
- (void)clientOnline:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid nickName:(NSString * _Null_unspecified)nickName userRole:(int32_t)role;
- (void)liveManagerClassOver:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager hasNewChatMessageWithChatArray:(NSArray * _Null_unspecified)newChatDictArray;
- (void)liveManagerChatMessageShouldClear:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager hasAnnounceContent:(NSString * _Null_unspecified)announceContent;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager onlineUserCountWith:(NSInteger)count;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager studentCanSpeak:(BOOL)canSpeak;
- (void)liveManagerTeacherDownHands:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager shouldShowVoteWithType:(DBYLiveManagerVoteType)voteType;
- (void)liveManagerShouldStopVote:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManagerShouldHideVote:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager voteChangeWithOptionIndex:(NSInteger)index optionCount:(NSInteger)count;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager voteEndWithOptionIndex:(NSInteger)index ontionSumCount:(NSInteger)count;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager teacherStatusChangedWithOnline:(BOOL)online name:(NSString * _Null_unspecified)name;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager teacherGiveMicToStudentWithUserInfo:(NSDictionary * _Null_unspecified)userInfo canSpeak:(BOOL)canSpeak;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager hasVideo:(BOOL)hasVideo inView:(UIView * _Null_unspecified)view;
- (void)liveManagerDidKickedOff:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManagerTeacherAskStudentOpenCamera:(DBYLiveManager * _Null_unspecified)manager;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager denyChatStatusChange:(BOOL)isDeny;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager canChat:(BOOL)canChat;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager receivedQuestion:(NSDictionary * _Null_unspecified)dict;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager removedQuestion:(NSString * _Null_unspecified)questionId;
- (void)initVideoRecorder:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid SWIFT_METHOD_FAMILY(none);
- (void)destroyVideoRecorder:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager interActionListChange:(NSArray<DBYInteractionModel *> * _Null_unspecified)list type:(DBYInteractionType)type;
- (void)willReceivedVideoData:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid;
- (void)willInterruptVideoData:(DBYLiveManager * _Null_unspecified)liveManager userId:(NSString * _Null_unspecified)uid;
- (void)liveManager:(DBYLiveManager * _Null_unspecified)manager thumbupWithCount:(NSInteger)count userName:(NSString * _Null_unspecified)userName;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo21DBYPlaybackController")
@interface DBYPlaybackController : DBY1VNController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo20DBYOfflineController")
@interface DBYOfflineController : DBYPlaybackController
@property (nonatomic, copy) NSString * _Nullable roomID;
@property (nonatomic, copy) NSString * _Nullable offlineKey;
@property (nonatomic, copy) NSString * _Nullable classFilePath;
@property (nonatomic) BOOL hasVideo;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end







@class DBYOfflinePlayBackManager;

@interface DBYOfflineController (SWIFT_EXTENSION(DBYSharedVideo)) <DBYOfflinePlayBackManagerDelegate>
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager thumbupWithCount:(NSInteger)count;
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager playStateIsPlaying:(BOOL)isPlaying;
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager hasVideo:(BOOL)hasVideo inView:(UIView * _Null_unspecified)view;
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager hasNewChatMessageWithChatArray:(NSArray * _Null_unspecified)newChatDictArray;
- (void)offlinePlayBackManagerChatMessageShouldClear:(DBYOfflinePlayBackManager * _Null_unspecified)manager;
- (void)offlinePlayBackManager:(DBYOfflinePlayBackManager * _Null_unspecified)manager isPlayingAtProgress:(float)progress time:(NSTimeInterval)time;
- (void)offlinePlayBackManagerFinishedPlay:(DBYOfflinePlayBackManager * _Null_unspecified)manager;
@end


SWIFT_CLASS("_TtC14DBYSharedVideo19DBYOnlineController")
@interface DBYOnlineController : DBYPlaybackController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end









@class DBYOnlinePlayBackManager;

@interface DBYOnlineController (SWIFT_EXTENSION(DBYSharedVideo)) <DBYOnlinePlayBackManagerDelegate>
- (void)playBackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager onlineWithuserId:(NSString * _Null_unspecified)uid nickName:(NSString * _Null_unspecified)nickName userRole:(int32_t)role;
- (void)playBackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager thumbupWithCount:(NSInteger)count;
- (void)playbackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager playStateChange:(BOOL)isPlaying;
- (void)playbackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager hasNewChatMessageWithChatArray:(NSArray * _Null_unspecified)newChatDictArray;
- (void)playBackManagerChatMessageShouldClear:(DBYOnlinePlayBackManager * _Null_unspecified)manager;
- (void)playBackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager totalTime:(NSTimeInterval)time;
- (void)playBackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager playedAtTime:(NSTimeInterval)time;
- (void)playbackManagerDidPlayEnd:(DBYOnlinePlayBackManager * _Null_unspecified)manager;
- (void)playbackManager:(DBYOnlinePlayBackManager * _Null_unspecified)manager hasVideo:(BOOL)hasVideo inView:(UIView * _Null_unspecified)view;
@end



SWIFT_CLASS("_TtC14DBYSharedVideo17DBYViewController")
@interface DBYViewController : UIViewController
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibName OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

















#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
